<?php
	include ('connection.php');
	$id=$_SESSION['id'];
	if(@$_POST['simpan']){
		$h1 = $_POST['halte1']; $h2 = $_POST['halte2']; $h3 = $_POST['halte3']; $h4 = $_POST['halte4']; 
		$h5 = $_POST['halte5']; $h6 = $_POST['halte6']; $h7 = $_POST['halte7']; $h8 = $_POST['halte8'];
		$h9 = $_POST['halte9']; $h10 = $_POST['halte10']; $h11 = $_POST['halte11']; $h12 = $_POST['halte12'];
		$h13 = $_POST['halte13']; $h14 = $_POST['halte14']; $h15 = $_POST['halte15']; $h16 = $_POST['halte16'];
		$h17 = $_POST['halte17']; $h17 = $_POST['halte17']; $h18 = $_POST['halte18']; $h19 = $_POST['halte19'];
		$h20 = $_POST['halte20']; $h21 = $_POST['halte21'];
		
	$sql_update1 = "UPDATE jadwalfix SET tiba = '".$h1."' WHERE jadwal_fix = '".$id."01'";
	$sql_update2 = "UPDATE jadwalfix SET tiba = '".$h2."' WHERE jadwal_fix = '".$id."02'";
	$sql_update3 = "UPDATE jadwalfix SET tiba = '".$h3."' WHERE jadwal_fix = '".$id."03'";
	$sql_update4 = "UPDATE jadwalfix SET tiba = '".$h4."' WHERE jadwal_fix = '".$id."04'";
	$sql_update5 = "UPDATE jadwalfix SET tiba = '".$h5."' WHERE jadwal_fix = '".$id."05'";
	$sql_update6 = "UPDATE jadwalfix SET tiba = '".$h6."' WHERE jadwal_fix = '".$id."06'";
	$sql_update7 = "UPDATE jadwalfix SET tiba = '".$h7."' WHERE jadwal_fix = '".$id."07'";
	$sql_update8 = "UPDATE jadwalfix SET tiba = '".$h8."' WHERE jadwal_fix = '".$id."08'";
	$sql_update9 = "UPDATE jadwalfix SET tiba = '".$h9."' WHERE jadwal_fix = '".$id."09'";
	$sql_update10 = "UPDATE jadwalfix SET tiba = '".$h10."' WHERE jadwal_fix = '".$id."10'";
	$sql_update11 = "UPDATE jadwalfix SET tiba = '".$h11."' WHERE jadwal_fix = '".$id."11'";
	$sql_update12 = "UPDATE jadwalfix SET tiba = '".$h12."' WHERE jadwal_fix = '".$id."12'";
	$sql_update13 = "UPDATE jadwalfix SET tiba = '".$h13."' WHERE jadwal_fix = '".$id."13'";
	$sql_update14 = "UPDATE jadwalfix SET tiba = '".$h14."' WHERE jadwal_fix = '".$id."14'";
	$sql_update15 = "UPDATE jadwalfix SET tiba = '".$h15."' WHERE jadwal_fix = '".$id."15'";
	$sql_update16 = "UPDATE jadwalfix SET tiba = '".$h16."' WHERE jadwal_fix = '".$id."16'";
	$sql_update17 = "UPDATE jadwalfix SET tiba = '".$h17."' WHERE jadwal_fix = '".$id."17'";
	$sql_update18 = "UPDATE jadwalfix SET tiba = '".$h18."' WHERE jadwal_fix = '".$id."18'";
	$sql_update19 = "UPDATE jadwalfix SET tiba = '".$h19."' WHERE jadwal_fix = '".$id."19'";
	$sql_update20 = "UPDATE jadwalfix SET tiba = '".$h20."' WHERE jadwal_fix = '".$id."20'";
	$sql_update21 = "UPDATE jadwalfix SET tiba = '".$h21."' WHERE jadwal_fix = '".$id."21'";
	mysql_query($sql_update1);
	mysql_query($sql_update2);
	mysql_query($sql_update3);
	mysql_query($sql_update4);
	mysql_query($sql_update5);
	mysql_query($sql_update6);
	mysql_query($sql_update7);
	mysql_query($sql_update8);
	mysql_query($sql_update9);
	mysql_query($sql_update10);
	mysql_query($sql_update11);
	mysql_query($sql_update12);
	mysql_query($sql_update13);
	mysql_query($sql_update14);
	mysql_query($sql_update15);
	mysql_query($sql_update16);
	mysql_query($sql_update17);
	mysql_query($sql_update18);
	mysql_query($sql_update19);
	mysql_query($sql_update20);
	mysql_query($sql_update21);

	$sql_update1 = "UPDATE jadwal SET tiba = '".$h1."' WHERE no_jadwal = '".$id."01'";
	$sql_update2 = "UPDATE jadwal SET tiba = '".$h2."' WHERE no_jadwal = '".$id."02'";
	$sql_update3 = "UPDATE jadwal SET tiba = '".$h3."' WHERE no_jadwal = '".$id."03'";
	$sql_update4 = "UPDATE jadwal SET tiba = '".$h4."' WHERE no_jadwal = '".$id."04'";
	$sql_update5 = "UPDATE jadwal SET tiba = '".$h5."' WHERE no_jadwal = '".$id."05'";
	$sql_update6 = "UPDATE jadwal SET tiba = '".$h6."' WHERE no_jadwal = '".$id."06'";
	$sql_update7 = "UPDATE jadwal SET tiba = '".$h7."' WHERE no_jadwal = '".$id."07'";
	$sql_update8 = "UPDATE jadwal SET tiba = '".$h8."' WHERE no_jadwal = '".$id."08'";
	$sql_update9 = "UPDATE jadwal SET tiba = '".$h9."' WHERE no_jadwal = '".$id."09'";
	$sql_update10 = "UPDATE jadwal SET tiba = '".$h10."' WHERE no_jadwal = '".$id."10'";
	$sql_update11 = "UPDATE jadwal SET tiba = '".$h11."' WHERE no_jadwal = '".$id."11'";
	$sql_update12 = "UPDATE jadwal SET tiba = '".$h12."' WHERE no_jadwal = '".$id."12'";
	$sql_update13 = "UPDATE jadwal SET tiba = '".$h13."' WHERE no_jadwal = '".$id."13'";
	$sql_update14 = "UPDATE jadwal SET tiba = '".$h14."' WHERE no_jadwal = '".$id."14'";
	$sql_update15 = "UPDATE jadwal SET tiba = '".$h15."' WHERE no_jadwal = '".$id."15'";
	$sql_update16 = "UPDATE jadwal SET tiba = '".$h16."' WHERE no_jadwal = '".$id."16'";
	$sql_update17 = "UPDATE jadwal SET tiba = '".$h17."' WHERE no_jadwal = '".$id."17'";
	$sql_update18 = "UPDATE jadwal SET tiba = '".$h18."' WHERE no_jadwal = '".$id."18'";
	$sql_update19 = "UPDATE jadwal SET tiba = '".$h19."' WHERE no_jadwal = '".$id."19'";
	$sql_update20 = "UPDATE jadwal SET tiba = '".$h20."' WHERE no_jadwal = '".$id."20'";
	$sql_update21 = "UPDATE jadwal SET tiba = '".$h21."' WHERE no_jadwal = '".$id."21'";
	mysql_query($sql_update1);
	mysql_query($sql_update2);
	mysql_query($sql_update3);
	mysql_query($sql_update4);
	mysql_query($sql_update5);
	mysql_query($sql_update6);
	mysql_query($sql_update7);
	mysql_query($sql_update8);
	mysql_query($sql_update9);
	mysql_query($sql_update10);
	mysql_query($sql_update11);
	mysql_query($sql_update12);
	mysql_query($sql_update13);
	mysql_query($sql_update14);
	mysql_query($sql_update15);
	mysql_query($sql_update16);
	mysql_query($sql_update17);
	mysql_query($sql_update18);
	mysql_query($sql_update19);
	mysql_query($sql_update20);
	mysql_query($sql_update21);

	echo("<script>location.href = 'inputjadwal.php';</script>");
	}
	?>